[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1 = "0.10.6"
libflate = "2.0.0"
chrono = "0.4.31"
flate2 = "1.0"
utils = { path = "../utils" }
gtk = "0.17.1"

